name: C/C++ CI

on: [push]

jobs:
  build-linux-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,ubuntu-18.04,ubuntu-16.04,macOS-latest,macos]
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release
    - name: run
      run: cd build && ./gactions
      
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    steps:
    # powershell requires -and instead of &&
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir "build" && cd build && cmake ..
      shell: cmd
    - name: build
      run: cmake --build build --config Release
      shell: cmd
    - name: run
      run: cd build && dir && gactions
      shell: cmd

